### ISSUE TITLE
Claudie marketing activities

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#146]
This epic concerns activities in the interest of marketing Claudie to potential clients.

One example idea of that could be to prepare a demo/presentation introducing Claudie and showing it in action.
This would be useful to have, because it could be repeated or even published.

### a little summary

tl;dr: we'd like ourselves some:
- [ ] presentation
- [x] video on technical aspects aimed at engineers (#350)
- [x] marketing video (aimed at not-necessarily-engineers) - related to the previous point
- [ ] [asciicast](asciicast.io) demonstrating awesomeness of Claudie
- [ ] mailing list for Claudie's landing page Subscribe button
