### ISSUE TITLE
Claudie is going open-source :rocket: :moon:  

### ISSUE THREAD

**Issue by MarioUhrik** [Berops/claudie#171]
We've decided that Claudie is going to be completely open sourced (announced at a team meeting on 6 June 2022).
The purposes of going open source are to boost the trustworthiness and brand awareness of Claudie and Berops.

Unfortunately, before we can go open source, there is surely a lot of preparatory work to be done.
(For example, ~~git-crypt secrets~~, ~~removal of other private information from git/github~~, github runner & pipeline design, ~~MVP being completed~~, ~~PoC being completed~~, ~~README~~, ~~git history containing leaked credentials~~, ~~Docker registry has been made public~~, ~~release marketing campaign planned~~, ~~plan how to gauge the success/failure of the release~~, etc.)
The purpose of this task is to compose and then complete a list of tasks to be done as preparation before going open source.

### Exit criteria:
- [x] All tasks to be done as part of `platform` becoming open source are opened
- [x] All tasks opened above are completed
- [x] Claudie is open source
- [ ] Success/failure of the release is evaluated
