### ISSUE TITLE
Feature: LoadBalancing

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#44]
### Motivation:
We need to ensure that certain entry-points to the cluster will be highly available.

### Description:
Every K8s cluster needs to have loadbalancers at least for Ingress and K8s API traffic. Eventually this should be easily configurable for other types of LBs (TCP, UDP, Nodeports) The catch here is that the solution needs to work:
- in hybrid-cloud setups
- in multi-cloud setups

We might need to explore the possibilities of using LB-as-a-Service (from cloud-providers) vs home-made (e.g. haproxy) deployments. Understand the availability of this solution.

### Exit criteria:
- [x] Configuration pattern has been designed
- [x] API docs are updated
- [x] Basic tests are written
- [x] LB functionality is implemented
