### ISSUE TITLE
Storage System

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#50]
### Motivation:
We need to figure out a storage system to enable stateful workloads.

### Description:
Ability to run stateful workloads is a must. At the same time running stateful workloads is complex. Here the complexity is on another level considering the multi-/hybrid-cloud environment. At first a basic solution for most common use-cases will do.

### Exit criteria:
- [x] Propose a way of dealing with stateful workloads
- [x] Implement the chosen storage solution
- [x] Add E2E (and other) tests to cover the storage solution
- [x] Add documentation to cover the storage solution
- [x] Create tasks for implementing the above :point_up:
